# Generated by Django 3.0.2 on 2020-02-03 10:50

import core.mixin_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
            bases=(models.Model, core.mixin_model.TimestampMixin),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.Category')),
            ],
            bases=(models.Model, core.mixin_model.TimestampMixin),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='One and only image-field')),
                ('name', models.CharField(max_length=128, verbose_name='Text shown to the buyer')),
                ('description', models.TextField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
            bases=(models.Model, core.mixin_model.TimestampMixin),
        ),
        migrations.CreateModel(
            name='OfferVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_price', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('_is_active', models.BooleanField(default=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='menu.Offer')),
            ],
            bases=(models.Model, core.mixin_model.TimestampMixin),
        ),
        migrations.CreateModel(
            name='MenuItemVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_name', models.CharField(default='default', max_length=128, verbose_name='Internal name of the menu-variation')),
                ('name', models.CharField(max_length=128, verbose_name='Name to show to the clients')),
                ('description', models.TextField(null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='menu.MenuItem')),
                ('offer_variations', models.ManyToManyField(to='menu.OfferVariation')),
            ],
            bases=(models.Model, core.mixin_model.TimestampMixin),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='menu.Offer'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the extras stuff')),
                ('additional_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Additional price to order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='menu.Category')),
                ('offer_variations', models.ManyToManyField(related_name='extras', to='menu.OfferVariation')),
            ],
            bases=(models.Model, core.mixin_model.TimestampMixin),
        ),
        migrations.AddConstraint(
            model_name='menuitemvariation',
            constraint=models.UniqueConstraint(condition=models.Q(is_default=True), fields=('menu_item', 'is_default'), name='only_one_default'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemvariation',
            unique_together={('menu_item', 'variation_name')},
        ),
    ]
