# Generated by Django 3.0.2 on 2020-01-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='menuitemvariation',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='menu.MenuItem'),
        ),
        migrations.AddField(
            model_name='menuitemvariation',
            name='offer_variations',
            field=models.ManyToManyField(to='menu.OfferVariation'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.Category'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='extra',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='menu.Category'),
        ),
        migrations.AddField(
            model_name='extra',
            name='offer_variations',
            field=models.ManyToManyField(related_name='extras', to='menu.OfferVariation'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemvariation',
            unique_together={('menu_item', 'variation_name')},
        ),
    ]
