# Generated by Django 3.0.2 on 2020-01-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200131_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='offers',
            field=models.ManyToManyField(null=True, related_name='menu_items', to='menu.Offer'),
        ),
    ]
