# Generated by Django 3.0.2 on 2020-01-31 07:41

import core.mixin_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512)),
                ('street', models.CharField(max_length=512)),
                ('zip_code', models.CharField(max_length=10)),
                ('formated_address', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=32)),
                ('country', models.CharField(default='Romania', max_length=32)),
            ],
            bases=(models.Model, core.mixin_model.TimestampMixin),
        ),
    ]
